Provide screenshot for paused sync state
iterate-ch/docs pull request #114
Opened 2021-12-24 15:29 UTC by Cassie205

Adding Screenshot for "Paused Sync" state and updating alt image title

2022-01-04 09:52 UTC, AliveDevil requested changes

2022-01-04 09:52 UTC, AliveDevil commented on cyberduck/bookmarks.md
> +:alt: HTTP ULR
```suggestion
:alt: HTTP URL
```

2022-01-04 09:52 UTC, AliveDevil commented on cyberduck/connection.md
> +:alt: Proxy Configuration FTP/ SFTP
```suggestion
:alt: Proxy Configuration FTP/SFTP
```

2022-01-06 13:22 UTC, tatze96 requested changes

2022-01-06 13:22 UTC, tatze96 commented on cyberduck/transfer.md
> +:alt: Tranfsers
Change "Tranfsers" to " Transfers"

2022-01-06 13:22 UTC, tatze96 commented on protocols/dropbox.md
> +:alt: Bropbox Drive Icon
Change "Bropbox" to "Dropbox"

2022-01-07 09:07 UTC, tatze96 approved these changes

2022-01-11 10:20 UTC, AliveDevil approved these changes

2022-01-11 10:20 UTC, merged