Updated OAuth Reset Information
iterate-ch/docs pull request #214
Opened 2022-06-17 08:35 UTC by tatze96

2022-06-17 08:44 UTC, dkocher requested changes
It should not be required to manually delete saved tokens from the keychain or credentials manager. Instead, creating a new bookmark will start a new authentication flow allowing the user to login with a different user.

2022-06-17 08:44 UTC, dkocher commented on protocols/dropbox.md
> +If you have accidentally logged in with the wrong Dropbox Account or want to change the login of the Dropbox bookmark you can reset the OAuth token by deleting the entries related to `duck:dropbox?us
On macOS the entries in the keychain are named `api.dropboxapi.com`.

2022-06-17 08:44 UTC, dkocher commented on protocols/google_cloud_storage.md
> +If you have accidentally logged in with the wrong Google Cloud Storage username or want to change the login of the Google Cloud Storage bookmark you can reset the OAuth token by deleting the entries
On macOS the entries in the keychain are named `accounts.google.com`.

2022-06-17 08:44 UTC, dkocher commented on protocols/google_drive.md
> +If you have accidentally logged in with the wrong Google Drive Account or want to change the login of the Google Drive bookmark you can reset the OAuth token by deleting the entries related to `duck:
On macOS the entries in the keychain are named `accounts.google.com`.

2022-06-17 08:44 UTC, dkocher commented on protocols/onedrive.md
> +If you have accidentally logged in with the wrong OneDrive Account or want to change the login of the OneDrive bookmark you can reset the OAuth token by deleting the entries related to `duck:onedrive
On macOS the entries in the keychain are named `login.microsoftonline.com `.

2022-06-17 10:21 UTC, Cassie205 approved these changes

2022-06-20 08:44 UTC, dkocher requested changes

2022-06-20 08:44 UTC, dkocher commented on protocols/dropbox.md
> +Alternatively, you can reset the OAuth token by deleting the entries related to `duck:dropbox?user=(user)` out of the *Windows Credential Manager* or on macOS the entries related to `https://Dropbox
On macOS the entries can be found by _Account_ named `Dropbox (Email) OAuth2 Access Token` or _Name_ `api.dropboxapi.com`.

2022-06-20 11:19 UTC, dkocher approved these changes

2022-06-20 14:30 UTC, merged