Add Seagate and fix some issues
iterate-ch/docs pull request #249
Opened 2022-07-29 09:41 UTC by Cassie205

2022-08-03 13:09 UTC, tatze96 requested changes

2022-08-03 13:09 UTC, tatze96 commented on protocols/s3/seagate.md
> +The prompt contailing the access key information will only be displayed once. Make sure to save the details for future use.
Change "contailing" to "containing"

2022-08-08 12:27 UTC, dkocher approved these changes

2022-08-08 12:29 UTC, tatze96 approved these changes

2022-08-08 12:29 UTC, merged