added sftptogo to protocols/index
iterate-ch/docs pull request #350
Opened 2023-03-22 11:08 UTC by saggineumann

Somehow missed this in yesterday's PR 🤦

2023-03-22 11:15 UTC, AliveDevil commented
We could just pay more attention to the build logs 🙃

https://github.com/iterate-ch/docs/pull/346/checks#step:4:236

2023-03-22 12:35 UTC, dkocher requested changes
We should add a _Providers_ section to the [SFTP](https://docs.cyberduck.io/protocols/sftp/) page instead as in [WebDAV](https://docs.cyberduck.io/protocols/webdav/#providers).

2023-03-22 12:35 UTC, dkocher commented on protocols/index.md
> +sftptogo
In general we will not want to have a single provider in the top level protocol list. Exceptions apply.

2023-03-22 12:35 UTC, dkocher commented on protocols/index.md
> +### [SFTP To Go](sftptogo.md)
In general we will not want to have a single provider in the top level protocol list. Exceptions apply.

2023-03-22 12:35 UTC, dkocher commented on protocols/index.md
> +| SFTP To Go           | ✅ ||
No need to list specific provider as SFTP in general applies.

2023-03-22 13:02 UTC, saggineumann commented
@dkocher no problem - I followed files.com's as an example. Shall I go ahead and add the providers section to the SFTP page? Should I move anything besides SFTP To Go in there?

2023-03-22 13:35 UTC, dkocher commented
> @dkocher also note that SFTP, FTPS and S3 are all protocols that work with SFTP To Go - should I add providers to these pages too?

We may want to restructure this later.

- [ ] #351

2023-03-23 15:47 UTC, saggineumann commented
@dkocher care to review again please?

2023-03-24 07:41 UTC, dkocher commented
Looks good to me. Would you mind squashing the two commits.

2023-03-26 07:51 UTC, saggineumann commented
squashed

2023-03-26 13:53 UTC, dkocher approved these changes

2023-03-28 10:27 UTC, merged