Documentation extension "Segmented Downloads"
iterate-ch/docs pull request #49
Opened 2021-09-27 14:35 UTC by Cassie205

2021-09-27 14:46 UTC, dkocher commented on Cyberduck/Download.md
> +The segments will be merged automatically after all parts are downloaded.
Failed segments can be resumed by choosing _Resume_ for a failed transfer.

2021-09-29 08:30 UTC, dkocher requested changes

2021-09-29 20:29 UTC, dkocher requested changes

2021-09-29 20:29 UTC, dkocher commented on Cyberduck/Download.md
> +The segments will be merged automatically after all parts are downloaded. Merging the segmentsmay take a considerable amount of time depending of the system.
Typo `segmentsmay`

2021-09-29 20:29 UTC, dkocher commented on Cyberduck/Download.md
> +The segments will be merged automatically after all parts are downloaded. Merging the segmentsmay take a considerable amount of time depending of the system.
depend *on* sth. Not clear what *system*. Omit or replace with *computer*.

2021-09-30 09:22 UTC, dkocher approved these changes

2021-09-30 11:11 UTC, tatze96 approved these changes

2021-09-30 11:18 UTC, merged