Document SSH user certificate authentication
iterate-ch/docs pull request #530
Opened 2024-05-16 11:47 UTC by AliveDevil

2024-05-18 14:10 UTC, dkocher requested changes

2024-05-18 14:10 UTC, dkocher commented on protocols/sftp/index.md
> +Applies to Cyberduck 8.9 and Mountain Duck 4.16
```suggestion
```{important}
* Cyberduck [8.9.0](https://cyberduck.io/changelog/) or later required
* Mountain Duck [4.16.0](https://mountainduck.io/changelog/) or later required
```
```

2024-05-21 10:38 UTC, AliveDevil commented on protocols/sftp/index.md
> +The certificate file has to be suffixed by either "-cert.pub" or ".pub" to be eligible for authentication. The OpenSSH configuration directive `CertificateFile` is not used.
Not sure whether this needs a comment, as with any other public key authentication, the private key file has to be selected.

2024-05-21 11:06 UTC, AliveDevil commented on protocols/sftp/index.md
> +Pay attention to the server configuration and `PubkeyAcceptedAlgorithms`, which private key algorithms are allowed. The algorithm used is `${Private Key Type}-cert-v01@openssh.com`.
Removed the last sentence. Added all possible (?) values to Signatures.

2024-05-21 17:05 UTC, dkocher requested changes

2024-05-21 17:05 UTC, dkocher commented on protocols/sftp/index.md
> +Pay attention to the server configuration and `PubkeyAcceptedAlgorithms`, which private key algorithms are allowed
```
Pay attention to the server configuration and `PubkeyAcceptedAlgorithms` specifically which determines the allowed private key algorithms to authenticate with.
```

2024-05-21 17:05 UTC, dkocher commented on protocols/sftp/index.md
> +The certificate file has to be suffixed by either "-cert.pub" or ".pub" to be eligible for authentication. The OpenSSH configuration directive `CertificateFile` is not used.
It must be made clear which file has to be selected.

2024-05-21 17:05 UTC, dkocher commented on protocols/sftp/index.md
> +Pay attention to the server configuration and `PubkeyAcceptedAlgorithms`, which private key algorithms are allowed
Should we link to the OpenSSH documentation for the configuration directives?

2024-05-21 17:05 UTC, dkocher commented on protocols/sftp/index.md
> +Applies to SSH servers, which are configured with `TrustedUserCAKeys`, refer to your software vendor for configuration.
Should we link to the OpenSSH documentation for the configuration directives?

2024-05-21 17:05 UTC, dkocher commented on protocols/sftp/index.md
> +With Cyberduck 8.9 and Mountain Duck 4.16, support for
Drop the version requirement already clarified in note above.

2024-05-21 17:05 UTC, dkocher commented on protocols/sftp/index.md
> +- `ssh-ed25519-cert-v01@openssh.com`
Split into sections for _SSH Key Types_  and _SSH Certificates Key Types_.

2024-06-17 12:52 UTC, dkocher approved these changes

2024-06-17 12:52 UTC, merged