Update and rename selectel.md
iterate-ch/docs pull request #558
Opened 2024-08-02 11:29 UTC by Irk-Grishin

Selectel Storage API has changed from SWIFT to S3.

1) Updated links to the product.
2) Added a general description of the integration setup. 3) Added a link to detailed instruction.
4) Changed the folder for this file

2024-08-02 13:42 UTC, dkocher commented
Do you want to provide an updated connection profile [^1]?

[^1]: https://github.com/iterate-ch/profiles/blob/main/Selectel%20Cloud%20Storage.cyberduckprofile

2024-08-02 13:43 UTC, dkocher requested changes

2024-08-02 13:43 UTC, dkocher commented on protocols/s3/selectel.md
> +> [Selectel Cloud Storage](https://selectel.ru/en/services/cloud/storage/) is a durable S3 for developers and businesses.
The page is not found.

2024-08-02 21:27 UTC, Irk-Grishin reviewed
I've done

2024-08-03 17:32 UTC, Irk-Grishin commented on protocols/s3/selectel.md
> +> [Selectel Cloud Storage](https://selectel.ru/en/services/cloud/storage/) is a durable S3 for developers and businesses.
I fixed it.

2024-08-06 15:36 UTC, Irk-Grishin commented
@dkocher please tell me. What do I have to do to move this PR forward?

2024-08-13 12:45 UTC, dkocher requested changes

2024-08-13 12:45 UTC, dkocher commented on protocols/s3/selectel.md
> +- ```s3.ru-1.storage.selcloud.ru/<container_name>``` domain with Path-Style addressing, used if Virtual-Hosted addressing is not enabled.
Single ticks should suffice.

2024-08-13 12:45 UTC, dkocher commented on protocols/s3/selectel.md
> +- Select he S3 Selectel (or the Amazon S3 profile). To work with this profile, the container must have Virtual-Hosted addressing enabled, see the [Detailed instructions for connection](https://docs.s
Typo `Select the…`

2024-08-13 12:45 UTC, dkocher commented on protocols/s3/selectel.md
> +The integration Cyberduck with Selectel can be operated through a graphical or console client via the S3 API.
Not sure what you mean by `…can be operated through a graphical or console client via the S3 API.`.

2024-08-13 12:45 UTC, dkocher commented on protocols/s3/selectel.md
> +Access can be configured by a user with role Account Owner or User Administrator in Selectel S3.
Remove line breaks.

2024-08-13 12:45 UTC, dkocher commented on protocols/s3/selectel.md
> +### Configure access
```suggestion
### Configure Access
```

2024-08-13 12:45 UTC, dkocher commented on protocols/s3/selectel.md
> +### Customize the client⁠
The client is not customized. 

```suggestion
### Configuration
```

2024-08-13 12:45 UTC, dkocher commented on protocols/s3/selectel.md
> +- In the Server field, enter the domain s3.ru-1.storage.selcloud.ru, where ru-1 is the pool that hosts the object storage.
```suggestion
- In the _Server_ field, enter the domain `s3.ru-1.storage.selcloud.ru`, where ru-1 is the pool that hosts the object storage.
```

2024-08-13 12:45 UTC, dkocher commented on protocols/s3/selectel.md
> +- In the Access Key ID field, insert the value of the Access key field from S3-key.
```suggestion
- In the _Access Key ID_ field, insert the value of the Access key field from your S3 key.
```

2024-08-13 12:45 UTC, dkocher commented on protocols/s3/selectel.md
> +- In the Secret access key field, insert the value of the Secret key field from the S3 key.
```suggestion
- In the _Secret Access Key_ field, insert the value of the Secret key field from your S3 key.
```

2024-08-13 12:45 UTC, dkocher commented on protocols/s3/selectel.md
> +- Select he S3 Selectel (or the Amazon S3 profile). To work with this profile, the container must have Virtual-Hosted addressing enabled, see the [Detailed instructions for connection](https://docs.s
Add notice about optional installation of connection profile.

```
Connection profiles can be installed from *Preferences → Profiles*.
```

2024-10-11 13:33 UTC, Irk-Grishin reviewed
Let's move this MR forward

2024-10-12 19:25 UTC, dkocher commented
Unfortunately there was a conflicting edit in 927721ebb82b5a71bdf50b4addc69f1e7f0dc787. Please rebase this pull request.

2024-12-25 15:55 UTC, dkocher approved these changes

2024-12-25 16:00 UTC, dkocher approved these changes

2024-12-25 16:01 UTC, merged