Restructure S3 Providers
iterate-ch/docs pull request #576
Opened 2024-09-03 14:43 UTC by Cassie205

2024-09-03 15:52 UTC, dkocher commented
- [ ] Missing section with references for connection profiles of IBM Cloud Object Storage
- [ ] Missing reference for DreamObjects connection profile
- [ ] Missing reference for FileBase connection profile
- [ ] Missing reference for Storj connection profile

2024-09-03 15:53 UTC, dkocher requested changes
- [ ] Missing section with references for connection profiles of IBM Cloud Object Storage
- [ ] Missing reference for DreamObjects connection profile
- [ ] Missing reference for FileBase connection profile
- [ ] Missing reference for Storj connection profile

2024-09-19 15:37 UTC, dkocher approved these changes

2024-09-19 17:23 UTC, ylangisc approved these changes

2024-09-19 17:32 UTC, merged